base_model: meta-llama/Meta-Llama-3-8B-Instruct
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer
is_llama_derived_model: true
tokenizer_use_fast: true
hub_model_id: Llama-3-8B-spectrum-25

# load_in_8bit: true
# load_in_4bit: false
# strict: false

datasets:
  - path: deepanshdj/llama3_dataset_1k
    type: alpaca

dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./outputs/llama-3-8b-spectrum-25

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

# Model Layers for Llama-3-8B-Instruct (Spectrum with snr values (25%)):
unfrozen_parameters:
  - ^lm_head.weight$
  - ^model.embed_tokens.weight$
  # input_layernorm layers
  - model.layers.0.input_layernorm
  - model.layers.1.input_layernorm
  - model.layers.2.input_layernorm
  - model.layers.3.input_layernorm
  - model.layers.4.input_layernorm
  - model.layers.5.input_layernorm
  - model.layers.6.input_layernorm
  - model.layers.7.input_layernorm
  # lm_head layers
  # mlp.down_proj layers
  - model.layers.1.mlp.down_proj
  - model.layers.0.mlp.down_proj
  - model.layers.2.mlp.down_proj
  - model.layers.30.mlp.down_proj
  - model.layers.22.mlp.down_proj
  - model.layers.21.mlp.down_proj
  - model.layers.5.mlp.down_proj
  - model.layers.29.mlp.down_proj
  # mlp.gate_proj layers
  - model.layers.1.mlp.gate_proj
  - model.layers.2.mlp.gate_proj
  - model.layers.3.mlp.gate_proj
  - model.layers.0.mlp.gate_proj
  - model.layers.4.mlp.gate_proj
  - model.layers.25.mlp.gate_proj
  - model.layers.26.mlp.gate_proj
  - model.layers.5.mlp.gate_proj
  # mlp.up_proj layers
  - model.layers.4.mlp.up_proj
  - model.layers.0.mlp.up_proj
  - model.layers.3.mlp.up_proj
  - model.layers.5.mlp.up_proj
  - model.layers.7.mlp.up_proj
  - model.layers.6.mlp.up_proj
  - model.layers.2.mlp.up_proj
  - model.layers.1.mlp.up_proj
  # model.embed_tokens layers
  # model.norm layers
  # post_attention_layernorm layers
  - model.layers.0.post_attention_layernorm
  - model.layers.1.post_attention_layernorm
  - model.layers.2.post_attention_layernorm
  - model.layers.3.post_attention_layernorm
  - model.layers.4.post_attention_layernorm
  - model.layers.5.post_attention_layernorm
  - model.layers.6.post_attention_layernorm
  - model.layers.7.post_attention_layernorm
  # self_attn.k_proj layers
  - model.layers.29.self_attn.k_proj
  - model.layers.25.self_attn.k_proj
  - model.layers.23.self_attn.k_proj
  - model.layers.28.self_attn.k_proj
  - model.layers.21.self_attn.k_proj
  - model.layers.19.self_attn.k_proj
  - model.layers.22.self_attn.k_proj
  - model.layers.20.self_attn.k_proj
  # self_attn.o_proj layers
  - model.layers.14.self_attn.o_proj
  - model.layers.7.self_attn.o_proj
  - model.layers.5.self_attn.o_proj
  - model.layers.11.self_attn.o_proj
  - model.layers.9.self_attn.o_proj
  - model.layers.6.self_attn.o_proj
  - model.layers.13.self_attn.o_proj
  - model.layers.10.self_attn.o_proj
  # self_attn.q_proj layers
  - model.layers.13.self_attn.q_proj
  - model.layers.9.self_attn.q_proj
  - model.layers.10.self_attn.q_proj
  - model.layers.8.self_attn.q_proj
  - model.layers.14.self_attn.q_proj
  - model.layers.11.self_attn.q_proj
  - model.layers.0.self_attn.q_proj
  - model.layers.15.self_attn.q_proj
  # self_attn.v_proj layers
  - model.layers.26.self_attn.v_proj
  - model.layers.17.self_attn.v_proj
  - model.layers.28.self_attn.v_proj
  - model.layers.3.self_attn.v_proj
  - model.layers.29.self_attn.v_proj
  - model.layers.21.self_attn.v_proj
  - model.layers.16.self_attn.v_proj
  - model.layers.15.self_attn.v_proj

# adapter: lora
# lora_model_dir:
# lora_r: 32
# lora_alpha: 16
# lora_dropout: 0.05
# lora_target_linear: true
# lora_fan_in_fan_out:

wandb_project: llama-3-8B-spectrum
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 2
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
eval_steps: 0.01
save_strategy: epoch
save_steps:
debug:
deepspeed: deepspeed_configs/zero2.json
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|end_of_text|>"
